### PR TITLE
Adding embedding path as an option argument

### LINKED ISSUE #56: Discrepancy between CLI entrypoint and run script
There seems to be a discrepancy between [_cli.py](https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_cli.py) and [_run.py](https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_run.py) in that `entrypoint_setup()` in `_cli.py` exposes an `output_path` argument to specify where to write the embeddings to but `run()` in `_run.py` does not offer the option to pass that as an argument; there it's hardcoded to `./embeddings`: https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_run.py#L8

I think we should either 

- add an `embeddings_path` argument to `run()` or 
- remove the `output_path` argument from `entrypoint_setup()`

### PR DESCRIPTION
**Pull request by atruslow**
Closes #56

- Changes `EMBEDDINGS_PATH ` to point to `./embeddings`
- Passes this argument to `_run.py::run`

### CODE REVIEW

**Comment by romatik** [comment]
@atruslow, thanks for the PR! 

Can you add an example on how to use this argument to the documentation (README and https://github.com/wayfair-incubator/extra-model/blob/main/docs/running_extra.md) + add it to changelog?

**Comment by atruslow** [comment]
@romatik I added the changelog and updated the docs. If you want to add a separate issue I can make those positional params into optional params so you don't need to supply them all to supply one of them. Thanks!

**Comment by romatik** [comment]
I've added this issue a while back specifically for that reason - https://github.com/wayfair-incubator/extra-model/issues/59. I can add more details there, but you pretty much got it - everything, but `input_filename` should be an option, so you can specify all other parameters in any order and quantity. Right now it's a bit clunky.

**Review by romatik — APPROVED** [review]

**Comment by romatik** [comment]
As far as this PR is concerned, I think it's good to go.
@atruslow, do you want to fix the #59 here as well or in a separate PR?

**Comment by atruslow** [comment]
@romatik - I'll just fix in a separate PR so I can merge this one in. Thanks !

**Comment by atruslow** [comment]
oh @romatik, looks like I can't merge because I don't have privs. If you are good please feel free to merge this, and then I'll start a new PR for breaking up the args.

**Comment by romatik** [comment]
merged

**Comment by romatik** [comment]
Fixes #63 too

**Pull request merged**
