### PR TITLE
Updated python-path-version in Docker file

### PR DESCRIPTION
**Pull request by Khairajani**
This was giving the error since the python version which is being used and the python path version was mismatching

### CODE REVIEW

**Comment by romatik** [comment]
hi @Khairajani, can you expand a bit more on what behavior you are trying to fix with this PR?

**Comment by Khairajani** [comment]
Hi @romatik, When I was using this repo for some tasks and I ran docker-compose with the freshly created virtual environment, there was some issue/error with finding the python path because of the version written in the Dockerfile.

I believe it's expected to 3.10 but the Dockerfile has 3.9, so it wasn't able to run docker properly. 
You can maybe validate this for being very sure about the mentioned scenario.

**Comment by romatik** [comment]
hm, do you think you need to have a docker image AND virtual environment? To me it sounds like you need to choose one way to manage your dependencies and stick to that. As it stands, I'm not sure it makes sense to merge the PR.

**Comment by romatik** [comment]
After looking a bit more into this I see your point and you are correct. Thanks for flagging, I'll merge it now!

**Review by romatik — APPROVED** [review]

**Pull request merged**
